[workspace]
authors = ["zetian-jia <jztneurosurgery@hotmail.com>"]
channels = ["conda-forge"]
name = "jbview"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=25.2.1,<25.3"
